name: Build / Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
    - name: Install Mock
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          mock
    - name: install prereqs
      run: sudo apt install autoconf-archive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make distribution source tarball
      run: make dist
    - name: build srpm (epel-7)
      run: sudo mock -r epel-7-x86_64 --buildsrpm --spec microsocks.spec --sources . --resultdir=/tmp/results
    - name: build rpm (epel-7)
      run: sudo mock -r epel-7-x86_64 --rebuild /tmp/results/*el7*.src.rpm --resultdir=/tmp/results
    - name: build srpm (epel-8)
      run: sudo mock -r epel-8-x86_64 --buildsrpm --spec microsocks.spec --sources . --resultdir=/tmp/results
    - name: build rpm (epel-8)
      run: sudo mock -r epel-8-x86_64 --rebuild /tmp/results/*el8*.src.rpm --resultdir=/tmp/results
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: /tmp/results/*.rpm
